#!/usr/bin/env python3
"""全球食材数据库生成器 - 涵盖上千种食材"""

import json
from pathlib import Path

KNOWLEDGE_DIR = Path(__file__).parent.parent / "knowledge" / "ingredients"

# 全球食材数据库
GLOBAL_INGREDIENTS = {
    "vegetables": {
        "leafy": [
            {"id": "romaine", "name": "罗马生菜", "en": "Romaine Lettuce", "cal": 17, "p": 1.2, "f": 0.3, "c": 3.3, "price": 8},
            {"id": "arugula", "name": "芝麻菜", "en": "Arugula", "cal": 25, "p": 2.6, "f": 0.7, "c": 3.7, "price": 15},
            {"id": "watercress", "name": "西洋菜", "en": "Watercress", "cal": 11, "p": 2.3, "f": 0.1, "c": 1.3, "price": 12},
            {"id": "endive", "name": "苦苣", "en": "Endive", "cal": 17, "p": 1.3, "f": 0.2, "c": 3.4, "price": 15},
            {"id": "radicchio", "name": "菊苣", "en": "Radicchio", "cal": 23, "p": 1.4, "f": 0.3, "c": 4.5, "price": 18},
            {"id": "bok_choy", "name": "小白菜", "en": "Bok Choy", "cal": 13, "p": 1.5, "f": 0.2, "c": 2.2, "price": 5},
            {"id": "napa_cabbage", "name": "大白菜", "en": "Napa Cabbage", "cal": 16, "p": 1.2, "f": 0.2, "c": 3.2, "price": 3},
            {"id": "savoy_cabbage", "name": "皱叶甘蓝", "en": "Savoy Cabbage", "cal": 27, "p": 2.0, "f": 0.1, "c": 6.0, "price": 8},
            {"id": "red_cabbage", "name": "紫甘蓝", "en": "Red Cabbage", "cal": 31, "p": 1.4, "f": 0.2, "c": 7.4, "price": 6},
            {"id": "brussels_sprout", "name": "抱子甘蓝", "en": "Brussels Sprout", "cal": 43, "p": 3.4, "f": 0.3, "c": 9.0, "price": 20},
            {"id": "kale", "name": "羽衣甘蓝", "en": "Kale", "cal": 49, "p": 4.3, "f": 0.9, "c": 8.8, "price": 15},
            {"id": "collard_greens", "name": "羽衣甘蓝", "en": "Collard Greens", "cal": 32, "p": 3.0, "f": 0.6, "c": 5.4, "price": 12},
            {"id": "mustard_greens", "name": "芥菜", "en": "Mustard Greens", "cal": 27, "p": 2.9, "f": 0.4, "c": 4.7, "price": 6},
            {"id": "turnip_greens", "name": "萝卜叶", "en": "Turnip Greens", "cal": 20, "p": 1.5, "f": 0.3, "c": 3.9, "price": 5},
            {"id": "beet_greens", "name": "甜菜叶", "en": "Beet Greens", "cal": 22, "p": 2.2, "f": 0.1, "c": 4.3, "price": 8},
            {"id": "swiss_chard", "name": "牛皮菜", "en": "Swiss Chard", "cal": 19, "p": 1.8, "f": 0.2, "c": 3.7, "price": 10},
            {"id": "sorrel", "name": "酸模", "en": "Sorrel", "cal": 22, "p": 2.0, "f": 0.7, "c": 3.2, "price": 15},
            {"id": "dandelion", "name": "蒲公英叶", "en": "Dandelion Greens", "cal": 45, "p": 2.7, "f": 0.7, "c": 9.2, "price": 10},
            {"id": "purslane", "name": "马齿苋", "en": "Purslane", "cal": 20, "p": 2.0, "f": 0.4, "c": 3.4, "price": 8},
            {"id": "amaranth", "name": "苋菜", "en": "Amaranth", "cal": 23, "p": 2.5, "f": 0.3, "c": 4.0, "price": 8},
        ],
        "root": [
            {"id": "parsnip", "name": "欧洲萝卜", "en": "Parsnip", "cal": 75, "p": 1.2, "f": 0.3, "c": 18.0, "price": 12},
            {"id": "rutabaga", "name": "芜菁甘蓝", "en": "Rutabaga", "cal": 38, "p": 1.1, "f": 0.2, "c": 8.6, "price": 10},
            {"id": "jicama", "name": "豆薯", "en": "Jicama", "cal": 38, "p": 0.7, "f": 0.1, "c": 8.8, "price": 12},
            {"id": "celeriac", "name": "根芹", "en": "Celeriac", "cal": 42, "p": 1.5, "f": 0.3, "c": 9.2, "price": 15},
            {"id": "salsify", "name": "婆罗门参", "en": "Salsify", "cal": 82, "p": 3.3, "f": 0.2, "c": 18.6, "price": 20},
            {"id": "daikon", "name": "白萝卜", "en": "Daikon", "cal": 18, "p": 0.6, "f": 0.1, "c": 4.1, "price": 4},
            {"id": "turmeric", "name": "姜黄", "en": "Turmeric", "cal": 312, "p": 9.7, "f": 3.3, "c": 67.1, "price": 25},
            {"id": "galangal", "name": "南姜", "en": "Galangal", "cal": 71, "p": 1.1, "f": 0.5, "c": 15.8, "price": 20},
            {"id": "horseradish", "name": "辣根", "en": "Horseradish", "cal": 48, "p": 1.2, "f": 0.7, "c": 11.3, "price": 15},
            {"id": "wasabi_root", "name": "山葵", "en": "Wasabi Root", "cal": 109, "p": 4.8, "f": 0.6, "c": 24.0, "price": 80},
            {"id": "burdock", "name": "牛蒡", "en": "Burdock", "cal": 72, "p": 1.5, "f": 0.2, "c": 17.3, "price": 12},
            {"id": "lotus_root_asian", "name": "莲藕", "en": "Lotus Root", "cal": 74, "p": 2.6, "f": 0.1, "c": 17.2, "price": 10},
            {"id": "taro_asian", "name": "芋头", "en": "Taro", "cal": 112, "p": 1.5, "f": 0.2, "c": 26.5, "price": 8},
            {"id": "yam_asian", "name": "山药", "en": "Yam", "cal": 118, "p": 1.5, "f": 0.2, "c": 27.9, "price": 10},
            {"id": "cassava", "name": "木薯", "en": "Cassava", "cal": 160, "p": 1.4, "f": 0.3, "c": 38.1, "price": 8},
            {"id": "malanga", "name": "芋", "en": "Malanga", "cal": 98, "p": 1.5, "f": 0.2, "c": 23.1, "price": 12},
            {"id": "yautia", "name": "箭叶黄体芋", "en": "Yautia", "cal": 98, "p": 1.5, "f": 0.2, "c": 23.1, "price": 15},
        ],
        "fruit_vegetable": [
            {"id": "bell_pepper_red", "name": "红甜椒", "en": "Red Bell Pepper", "cal": 31, "p": 1.0, "f": 0.3, "c": 6.0, "price": 8},
            {"id": "bell_pepper_yellow", "name": "黄甜椒", "en": "Yellow Bell Pepper", "cal": 27, "p": 1.0, "f": 0.2, "c": 5.4, "price": 10},
            {"id": "bell_pepper_orange", "name": "橙甜椒", "en": "Orange Bell Pepper", "cal": 26, "p": 0.9, "f": 0.2, "c": 5.3, "price": 10},
            {"id": "poblano", "name": "波布拉诺辣椒", "en": "Poblano", "cal": 20, "p": 0.9, "f": 0.1, "c": 4.6, "price": 12},
            {"id": "jalapeno", "name": "墨西哥辣椒", "en": "Jalapeno", "cal": 29, "p": 0.9, "f": 0.4, "c": 6.5, "price": 10},
            {"id": "habanero", "name": "哈瓦那辣椒", "en": "Habanero", "cal": 40, "p": 1.8, "f": 0.4, "c": 8.8, "price": 15},
            {"id": "serrano", "name": "塞拉诺辣椒", "en": "Serrano", "cal": 32, "p": 1.7, "f": 0.4, "c": 6.7, "price": 12},
            {"id": "anaheim", "name": "阿纳海姆辣椒", "en": "Anaheim", "cal": 20, "p": 0.9, "f": 0.1, "c": 4.6, "price": 10},
            {"id": "cayenne", "name": "卡宴辣椒", "en": "Cayenne", "cal": 318, "p": 12.0, "f": 17.3, "c": 56.6, "price": 20},
            {"id": "ghost_pepper", "name": "魔鬼辣椒", "en": "Ghost Pepper", "cal": 40, "p": 2.0, "f": 0.5, "c": 8.0, "price": 30},
            {"id": "tomatillo", "name": "黏果酸浆", "en": "Tomatillo", "cal": 32, "p": 1.0, "f": 1.0, "c": 5.8, "price": 12},
            {"id": "cape_gooseberry", "name": "灯笼果", "en": "Cape Gooseberry", "cal": 53, "p": 1.9, "f": 0.7, "c": 11.2, "price": 15},
            {"id": "chayote", "name": "佛手瓜", "en": "Chayote", "cal": 19, "p": 0.8, "f": 0.1, "c": 4.5, "price": 8},
            {"id": "bottle_gourd", "name": "瓠瓜", "en": "Bottle Gourd", "cal": 14, "p": 0.6, "f": 0.1, "c": 3.4, "price": 5},
            {"id": "ridge_gourd", "name": "棱角丝瓜", "en": "Ridge Gourd", "cal": 20, "p": 1.2, "f": 0.2, "c": 4.4, "price": 6},
            {"id": "snake_gourd", "name": "蛇瓜", "en": "Snake Gourd", "cal": 18, "p": 0.5, "f": 0.1, "c": 4.2, "price": 8},
            {"id": "ivy_gourd", "name": "红瓜", "en": "Ivy Gourd", "cal": 18, "p": 1.2, "f": 0.1, "c": 3.6, "price": 10},
            {"id": "bitter_gourd_asian", "name": "苦瓜", "en": "Bitter Gourd", "cal": 17, "p": 1.0, "f": 0.2, "c": 3.7, "price": 6},
            {"id": "wax_gourd", "name": "冬瓜", "en": "Wax Gourd", "cal": 13, "p": 0.4, "f": 0.2, "c": 3.0, "price": 3},
            {"id": "long_bean", "name": "长豇豆", "en": "Long Bean", "cal": 47, "p": 2.8, "f": 0.4, "c": 8.4, "price": 6},
        ],
        "cruciferous": [
            {"id": "broccoli_raab", "name": "西兰花苔", "en": "Broccoli Raab", "cal": 22, "p": 3.2, "f": 0.5, "c": 2.9, "price": 15},
            {"id": "kohlrabi", "name": "苤蓝", "en": "Kohlrabi", "cal": 27, "p": 1.7, "f": 0.1, "c": 6.2, "price": 10},
            {"id": "romanesco", "name": "罗马花椰菜", "en": "Romanesco", "cal": 31, "p": 2.5, "f": 0.3, "c": 6.0, "price": 18},
            {"id": "cauliflower", "name": "花椰菜", "en": "Cauliflower", "cal": 25, "p": 1.9, "f": 0.3, "c": 5.0, "price": 6},
            {"id": "turnip", "name": "芜菁", "en": "Turnip", "cal": 28, "p": 0.9, "f": 0.1, "c": 6.4, "price": 5},
            {"id": "radish_red", "name": "红萝卜", "en": "Red Radish", "cal": 16, "p": 0.7, "f": 0.1, "c": 3.4, "price": 4},
            {"id": "radish_black", "name": "黑萝卜", "en": "Black Radish", "cal": 20, "p": 1.0, "f": 0.2, "c": 4.3, "price": 8},
            {"id": "watermelon_radish", "name": "西瓜萝卜", "en": "Watermelon Radish", "cal": 16, "p": 0.7, "f": 0.1, "c": 3.4, "price": 12},
            {"id": "daikon_asian", "name": "大根", "en": "Daikon", "cal": 18, "p": 0.6, "f": 0.1, "c": 4.1, "price": 4},
        ],
        "allium": [
            {"id": "shallot", "name": "青葱", "en": "Shallot", "cal": 72, "p": 2.5, "f": 0.1, "c": 16.8, "price": 12},
            {"id": "leek", "name": "韭葱", "en": "Leek", "cal": 61, "p": 1.5, "f": 0.3, "c": 14.2, "price": 10},
            {"id": "chive", "name": "细香葱", "en": "Chive", "cal": 30, "p": 3.3, "f": 0.7, "c": 4.4, "price": 8},
            {"id": "scallion_asian", "name": "葱", "en": "Scallion", "cal": 32, "p": 1.8, "f": 0.2, "c": 7.3, "price": 3},
            {"id": "garlic_scape", "name": "蒜薹", "en": "Garlic Scape", "cal": 30, "p": 1.6, "f": 0.1, "c": 7.0, "price": 10},
            {"id": "pearl_onion", "name": "珍珠洋葱", "en": "Pearl Onion", "cal": 42, "p": 1.0, "f": 0.1, "c": 10.0, "price": 8},
            {"id": "cipollini", "name": "意大利扁葱", "en": "Cipollini", "cal": 40, "p": 1.1, "f": 0.1, "c": 9.3, "price": 15},
            {"id": "ramps", "name": "野韭", "en": "Ramps", "cal": 35, "p": 2.0, "f": 0.3, "c": 7.1, "price": 25},
            {"id": "green_garlic", "name": "新蒜", "en": "Green Garlic", "cal": 30, "p": 1.5, "f": 0.2, "c": 6.5, "price": 12},
        ],
        "mushroom": [
            {"id": "portobello", "name": "波特贝勒菇", "en": "Portobello", "cal": 22, "p": 2.1, "f": 0.4, "c": 3.9, "price": 15},
            {"id": "cremini", "name": "克里米尼菇", "en": "Cremini", "cal": 22, "p": 2.5, "f": 0.1, "c": 4.3, "price": 12},
            {"id": "chanterelle", "name": "鸡油菌", "en": "Chanterelle", "cal": 38, "p": 1.5, "f": 0.5, "c": 6.9, "price": 50},
            {"id": "morel", "name": "羊肚菌", "en": "Morel", "cal": 31, "p": 3.1, "f": 0.6, "c": 5.1, "price": 80},
            {"id": "porcini", "name": "牛肝菌", "en": "Porcini", "cal": 34, "p": 3.1, "f": 0.4, "c": 6.0, "price": 60},
            {"id": "shiitake_asian", "name": "椎茸", "en": "Shiitake", "cal": 34, "p": 2.2, "f": 0.5, "c": 6.8, "price": 15},
            {"id": "maitake", "name": "舞茸", "en": "Maitake", "cal": 31, "p": 1.9, "f": 0.2, "c": 7.0, "price": 30},
            {"id": "reishi", "name": "灵芝", "en": "Reishi", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 100},
            {"id": "lion_mane", "name": "猴头菇", "en": "Lion's Mane", "cal": 35, "p": 2.5, "f": 0.3, "c": 7.6, "price": 40},
            {"id": "wood_ear_asian", "name": "木耳", "en": "Wood Ear", "cal": 37, "p": 1.5, "f": 0.2, "c": 6.5, "price": 15},
            {"id": "cloud_ear", "name": "云耳", "en": "Cloud Ear", "cal": 35, "p": 1.4, "f": 0.2, "c": 6.0, "price": 12},
            {"id": "enoki_asian", "name": "金针菇", "en": "Enoki", "cal": 37, "p": 2.7, "f": 0.3, "c": 7.8, "price": 8},
            {"id": "shimeji", "name": "玉蕈", "en": "Shimeji", "cal": 31, "p": 2.2, "f": 0.4, "c": 5.1, "price": 12},
            {"id": "king_oyster_asian", "name": "杏鲍菇", "en": "King Oyster", "cal": 34, "p": 1.3, "f": 0.4, "c": 8.3, "price": 10},
            {"id": "oyster_mushroom_asian", "name": "平菇", "en": "Oyster Mushroom", "cal": 33, "p": 3.3, "f": 0.4, "c": 6.1, "price": 8},
            {"id": "button_mushroom", "name": "白蘑菇", "en": "Button Mushroom", "cal": 22, "p": 3.1, "f": 0.3, "c": 3.3, "price": 8},
            {"id": "truffle_black", "name": "黑松露", "en": "Black Truffle", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 500},
            {"id": "truffle_white", "name": "白松露", "en": "White Truffle", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 800},
        ],
        "sprout": [
            {"id": "bean_sprout_mung", "name": "绿豆芽", "en": "Mung Bean Sprout", "cal": 31, "p": 3.0, "f": 0.2, "c": 5.9, "price": 4},
            {"id": "bean_sprout_soy", "name": "黄豆芽", "en": "Soy Bean Sprout", "cal": 122, "p": 13.1, "f": 6.0, "c": 9.6, "price": 5},
            {"id": "alfalfa", "name": "苜蓿芽", "en": "Alfalfa Sprout", "cal": 23, "p": 4.0, "f": 0.7, "c": 2.1, "price": 15},
            {"id": "broccoli_sprout", "name": "西兰花芽", "en": "Broccoli Sprout", "cal": 35, "p": 2.8, "f": 0.4, "c": 5.6, "price": 20},
            {"id": "radish_sprout", "name": "萝卜芽", "en": "Radish Sprout", "cal": 28, "p": 3.8, "f": 0.7, "c": 3.6, "price": 12},
        ],
        "seaweed": [
            {"id": "nori", "name": "海苔", "en": "Nori", "cal": 35, "p": 5.8, "f": 0.3, "c": 5.1, "price": 20},
            {"id": "wakame", "name": "裙带菜", "en": "Wakame", "cal": 45, "p": 3.0, "f": 0.6, "c": 9.1, "price": 25},
            {"id": "kombu", "name": "昆布", "en": "Kombu", "cal": 43, "p": 1.7, "f": 0.6, "c": 9.6, "price": 30},
            {"id": "dulse", "name": "掌状红皮藻", "en": "Dulse", "cal": 25, "p": 3.0, "f": 0.3, "c": 4.4, "price": 35},
            {"id": "irish_moss", "name": "爱尔兰苔", "en": "Irish Moss", "cal": 49, "p": 1.5, "f": 0.2, "c": 12.3, "price": 40},
            {"id": "spirulina", "name": "螺旋藻", "en": "Spirulina", "cal": 290, "p": 57.5, "f": 7.7, "c": 23.9, "price": 100},
            {"id": "chlorella", "name": "小球藻", "en": "Chlorella", "cal": 336, "p": 58.4, "f": 9.3, "c": 23.0, "price": 120},
        ],
    },
    "meat": {
        "beef": [
            {"id": "ribeye", "name": "肋眼牛排", "en": "Ribeye", "cal": 291, "p": 23.7, "f": 21.8, "c": 0, "price": 120},
            {"id": "tenderloin", "name": "菲力牛排", "en": "Tenderloin", "cal": 217, "p": 26.1, "f": 12.7, "c": 0, "price": 180},
            {"id": "new_york_strip", "name": "纽约客牛排", "en": "New York Strip", "cal": 244, "p": 25.6, "f": 15.4, "c": 0, "price": 150},
            {"id": "t_bone", "name": "T骨牛排", "en": "T-Bone", "cal": 247, "p": 24.2, "f": 16.3, "c": 0, "price": 160},
            {"id": "porterhouse", "name": "波特豪斯牛排", "en": "Porterhouse", "cal": 250, "p": 24.5, "f": 16.5, "c": 0, "price": 170},
            {"id": "flank", "name": "牛腹肉", "en": "Flank", "cal": 192, "p": 27.3, "f": 8.3, "c": 0, "price": 60},
            {"id": "skirt", "name": "牛裙肉", "en": "Skirt", "cal": 217, "p": 26.1, "f": 12.7, "c": 0, "price": 70},
            {"id": "hanger", "name": "牛膈肉", "en": "Hanger", "cal": 210, "p": 25.0, "f": 12.0, "c": 0, "price": 80},
            {"id": "chuck", "name": "牛肩肉", "en": "Chuck", "cal": 215, "p": 19.3, "f": 15.0, "c": 0, "price": 45},
            {"id": "round", "name": "牛腿肉", "en": "Round", "cal": 182, "p": 27.5, "f": 7.2, "c": 0, "price": 50},
            {"id": "shank", "name": "牛腱子", "en": "Shank", "cal": 180, "p": 25.0, "f": 8.0, "c": 0, "price": 40},
            {"id": "oxtail", "name": "牛尾", "en": "Oxtail", "cal": 250, "p": 18.0, "f": 19.0, "c": 0, "price": 55},
            {"id": "cheek", "name": "牛脸颊", "en": "Cheek", "cal": 200, "p": 20.0, "f": 12.0, "c": 0, "price": 45},
            {"id": "marrow", "name": "牛骨髓", "en": "Marrow", "cal": 786, "p": 2.5, "f": 84.0, "c": 0, "price": 35},
        ],
        "pork": [
            {"id": "loin", "name": "猪里脊", "en": "Pork Loin", "cal": 143, "p": 26.0, "f": 3.5, "c": 0, "price": 25},
            {"id": "tenderloin_pork", "name": "猪小里脊", "en": "Pork Tenderloin", "cal": 120, "p": 22.0, "f": 3.0, "c": 0, "price": 30},
            {"id": "shoulder_pork", "name": "梅花肉", "en": "Pork Shoulder", "cal": 210, "p": 18.0, "f": 15.0, "c": 0, "price": 22},
            {"id": "butt", "name": "猪臀肉", "en": "Pork Butt", "cal": 215, "p": 18.5, "f": 15.5, "c": 0, "price": 20},
            {"id": "sparerib", "name": "排骨", "en": "Sparerib", "cal": 278, "p": 18.0, "f": 22.0, "c": 0, "price": 30},
            {"id": "baby_back", "name": "小排骨", "en": "Baby Back Rib", "cal": 260, "p": 19.0, "f": 20.0, "c": 0, "price": 40},
            {"id": "chop", "name": "猪排", "en": "Pork Chop", "cal": 210, "p": 23.0, "f": 12.0, "c": 0, "price": 25},
            {"id": "ham_hock", "name": "猪蹄膀", "en": "Ham Hock", "cal": 250, "p": 20.0, "f": 18.0, "c": 0, "price": 15},
            {"id": "bacon", "name": "培根", "en": "Bacon", "cal": 541, "p": 37.0, "f": 42.0, "c": 1.4, "price": 35},
            {"id": "pancetta", "name": "意式培根", "en": "Pancetta", "cal": 460, "p": 30.0, "f": 37.0, "c": 0, "price": 50},
            {"id": "prosciutto", "name": "意式火腿", "en": "Prosciutto", "cal": 250, "p": 30.0, "f": 14.0, "c": 0, "price": 80},
            {"id": "chorizo", "name": "西班牙辣肠", "en": "Chorizo", "cal": 455, "p": 24.0, "f": 38.0, "c": 1.9, "price": 45},
            {"id": "sausage_italian", "name": "意式香肠", "en": "Italian Sausage", "cal": 340, "p": 19.0, "f": 28.0, "c": 4.0, "price": 30},
            {"id": "bratwurst", "name": "德国香肠", "en": "Bratwurst", "cal": 300, "p": 14.0, "f": 26.0, "c": 3.0, "price": 25},
        ],
        "lamb": [
            {"id": "rack", "name": "羊架", "en": "Rack of Lamb", "cal": 290, "p": 22.0, "f": 22.0, "c": 0, "price": 120},
            {"id": "lamb_shank", "name": "羊腱", "en": "Lamb Shank", "cal": 230, "p": 20.0, "f": 16.0, "c": 0, "price": 50},
            {"id": "lamb_loin", "name": "羊腰", "en": "Lamb Loin", "cal": 260, "p": 23.0, "f": 18.0, "c": 0, "price": 80},
            {"id": "lamb_ground", "name": "羊肉末", "en": "Ground Lamb", "cal": 282, "p": 17.0, "f": 23.0, "c": 0, "price": 45},
            {"id": "lamb_neck", "name": "羊颈肉", "en": "Lamb Neck", "cal": 240, "p": 19.0, "f": 18.0, "c": 0, "price": 35},
        ],
        "poultry": [
            {"id": "whole_chicken", "name": "整鸡", "en": "Whole Chicken", "cal": 215, "p": 18.0, "f": 15.0, "c": 0, "price": 18},
            {"id": "chicken_thigh", "name": "鸡腿", "en": "Chicken Thigh", "cal": 209, "p": 26.0, "f": 10.9, "c": 0, "price": 15},
            {"id": "chicken_drumstick", "name": "鸡小腿", "en": "Chicken Drumstick", "cal": 177, "p": 28.3, "f": 5.7, "c": 0, "price": 12},
            {"id": "chicken_tender", "name": "鸡柳", "en": "Chicken Tender", "cal": 130, "p": 24.0, "f": 3.0, "c": 0, "price": 20},
            {"id": "chicken_liver", "name": "鸡肝", "en": "Chicken Liver", "cal": 172, "p": 26.0, "f": 6.5, "c": 1.0, "price": 10},
            {"id": "turkey_breast", "name": "火鸡胸", "en": "Turkey Breast", "cal": 135, "p": 30.0, "f": 1.0, "c": 0, "price": 35},
            {"id": "turkey_leg", "name": "火鸡腿", "en": "Turkey Leg", "cal": 208, "p": 28.0, "f": 10.0, "c": 0, "price": 25},
            {"id": "duck_breast", "name": "鸭胸", "en": "Duck Breast", "cal": 201, "p": 23.5, "f": 11.2, "c": 0, "price": 45},
            {"id": "duck_leg", "name": "鸭腿", "en": "Duck Leg", "cal": 250, "p": 19.0, "f": 19.0, "c": 0, "price": 30},
            {"id": "quail", "name": "鹌鹑", "en": "Quail", "cal": 134, "p": 21.8, "f": 4.5, "c": 0, "price": 25},
            {"id": "squab", "name": "乳鸽", "en": "Squab", "cal": 197, "p": 17.5, "f": 14.0, "c": 0, "price": 40},
            {"id": "goose", "en": "Goose", "name": "鹅", "cal": 161, "p": 22.8, "f": 7.1, "c": 0, "price": 35},
            {"id": "cornish_hen", "name": "科尼什鸡", "en": "Cornish Hen", "cal": 180, "p": 20.0, "f": 10.0, "c": 0, "price": 30},
        ],
        "game": [
            {"id": "venison", "name": "鹿肉", "en": "Venison", "cal": 158, "p": 30.0, "f": 3.2, "c": 0, "price": 120},
            {"id": "bison", "name": "野牛肉", "en": "Bison", "cal": 146, "p": 28.4, "f": 2.4, "c": 0, "price": 100},
            {"id": "elk", "name": "麋鹿肉", "en": "Elk", "cal": 146, "p": 30.0, "f": 1.8, "c": 0, "price": 110},
            {"id": "wild_boar", "name": "野猪肉", "en": "Wild Boar", "cal": 160, "p": 28.0, "f": 4.0, "c": 0, "price": 80},
            {"id": "rabbit", "name": "兔肉", "en": "Rabbit", "cal": 173, "p": 33.0, "f": 3.5, "c": 0, "price": 40},
            {"id": "kangaroo", "name": "袋鼠肉", "en": "Kangaroo", "cal": 120, "p": 23.0, "f": 2.0, "c": 0, "price": 90},
        ],
    },
    "seafood": {
        "fish_freshwater": [
            {"id": "trout", "name": "鳟鱼", "en": "Trout", "cal": 148, "p": 22.0, "f": 6.2, "c": 0, "price": 45},
            {"id": "bass_freshwater", "name": "鲈鱼", "en": "Bass", "cal": 124, "p": 20.0, "f": 4.0, "c": 0, "price": 35},
            {"id": "perch", "name": "河鲈", "en": "Perch", "cal": 91, "p": 19.4, "f": 0.9, "c": 0, "price": 30},
            {"id": "pike", "name": "梭子鱼", "en": "Pike", "cal": 88, "p": 19.2, "f": 0.7, "c": 0, "price": 25},
            {"id": "walleye", "name": "大眼鲈", "en": "Walleye", "cal": 93, "p": 19.1, "f": 1.2, "c": 0, "price": 40},
            {"id": "catfish_asian", "name": "鲶鱼", "en": "Catfish", "cal": 95, "p": 16.4, "f": 2.8, "c": 0, "price": 18},
            {"id": "tilapia_asian", "name": "罗非鱼", "en": "Tilapia", "cal": 96, "p": 20.1, "f": 1.7, "c": 0, "price": 15},
            {"id": "carp_asian", "name": "鲤鱼", "en": "Carp", "cal": 127, "p": 17.8, "f": 5.6, "c": 0, "price": 12},
            {"id": "grass_carp_asian", "name": "草鱼", "en": "Grass Carp", "cal": 113, "p": 16.6, "f": 5.2, "c": 0, "price": 12},
            {"id": "silver_carp", "name": "鲢鱼", "en": "Silver Carp", "cal": 104, "p": 17.8, "f": 3.6, "c": 0, "price": 10},
            {"id": "bighead_carp", "name": "鳙鱼", "en": "Bighead Carp", "cal": 100, "p": 17.0, "f": 3.5, "c": 0, "price": 12},
        ],
        "fish_saltwater": [
            {"id": "tuna_bluefin", "name": "蓝鳍金枪鱼", "en": "Bluefin Tuna", "cal": 144, "p": 23.3, "f": 4.9, "c": 0, "price": 200},
            {"id": "tuna_yellowfin", "name": "黄鳍金枪鱼", "en": "Yellowfin Tuna", "cal": 108, "p": 24.4, "f": 0.5, "c": 0, "price": 80},
            {"id": "tuna_albacore", "name": "长鳍金枪鱼", "en": "Albacore Tuna", "cal": 128, "p": 23.6, "f": 3.0, "c": 0, "price": 60},
            {"id": "salmon_atlantic", "name": "大西洋三文鱼", "en": "Atlantic Salmon", "cal": 208, "p": 20.4, "f": 13.4, "c": 0, "price": 65},
            {"id": "salmon_king", "name": "帝王三文鱼", "en": "King Salmon", "cal": 231, "p": 25.7, "f": 13.8, "c": 0, "price": 120},
            {"id": "salmon_sockeye", "name": "红三文鱼", "en": "Sockeye Salmon", "cal": 168, "p": 21.3, "f": 8.6, "c": 0, "price": 70},
            {"id": "cod_atlantic", "name": "大西洋鳕鱼", "en": "Atlantic Cod", "cal": 82, "p": 17.8, "f": 0.7, "c": 0, "price": 50},
            {"id": "cod_pacific", "name": "太平洋鳕鱼", "en": "Pacific Cod", "cal": 85, "p": 18.3, "f": 0.8, "c": 0, "price": 45},
            {"id": "halibut", "name": "大比目鱼", "en": "Halibut", "cal": 111, "p": 22.5, "f": 1.6, "c": 0, "price": 80},
            {"id": "swordfish", "name": "剑鱼", "en": "Swordfish", "cal": 144, "p": 20.0, "f": 6.7, "c": 0, "price": 90},
            {"id": "mahi_mahi", "name": "鬼头刀", "en": "Mahi-Mahi", "cal": 85, "p": 18.5, "f": 0.7, "c": 0, "price": 60},
            {"id": "sea_bass_asian", "name": "海鲈鱼", "en": "Sea Bass", "cal": 97, "p": 18.4, "f": 2.0, "c": 0, "price": 55},
            {"id": "snapper", "name": "鲷鱼", "en": "Snapper", "cal": 100, "p": 20.5, "f": 1.3, "c": 0, "price": 50},
            {"id": "grouper", "name": "石斑鱼", "en": "Grouper", "cal": 92, "p": 18.8, "f": 1.0, "c": 0, "price": 60},
            {"id": "mackerel", "name": "鲭鱼", "en": "Mackerel", "cal": 205, "p": 18.6, "f": 13.9, "c": 0, "price": 25},
            {"id": "sardine", "name": "沙丁鱼", "en": "Sardine", "cal": 208, "p": 24.6, "f": 11.4, "c": 0, "price": 20},
            {"id": "anchovy", "name": "鳀鱼", "en": "Anchovy", "cal": 131, "p": 20.4, "f": 4.8, "c": 0, "price": 25},
            {"id": "herring", "name": "鲱鱼", "en": "Herring", "cal": 158, "p": 18.0, "f": 9.0, "c": 0, "price": 20},
            {"id": "barramundi", "name": "澳洲肺鱼", "en": "Barramundi", "cal": 95, "p": 19.0, "f": 1.5, "c": 0, "price": 65},
            {"id": "branzino", "name": "欧洲鲈鱼", "en": "Branzino", "cal": 97, "p": 18.4, "f": 2.0, "c": 0, "price": 70},
        ],
        "shellfish": [
            {"id": "lobster_maine", "name": "缅因龙虾", "en": "Maine Lobster", "cal": 89, "p": 19.0, "f": 0.5, "c": 0, "price": 150},
            {"id": "lobster_spiny", "name": "刺龙虾", "en": "Spiny Lobster", "cal": 92, "p": 19.5, "f": 1.0, "c": 0, "price": 120},
            {"id": "shrimp_tiger", "name": "老虎虾", "en": "Tiger Shrimp", "cal": 100, "p": 20.0, "f": 1.5, "c": 0, "price": 60},
            {"id": "shrimp_king", "name": "国王虾", "en": "King Shrimp", "cal": 105, "p": 21.0, "f": 1.8, "c": 0, "price": 80},
            {"id": "prawn", "name": "大虾", "en": "Prawn", "cal": 99, "p": 20.0, "f": 1.5, "c": 0, "price": 45},
            {"id": "crab_king", "name": "帝王蟹", "en": "King Crab", "cal": 97, "p": 19.3, "f": 1.5, "c": 0, "price": 200},
            {"id": "crab_snow", "name": "雪蟹", "en": "Snow Crab", "cal": 90, "p": 18.5, "f": 1.2, "c": 0, "price": 120},
            {"id": "crab_dungeness", "name": "珍宝蟹", "en": "Dungeness Crab", "cal": 87, "p": 18.1, "f": 1.0, "c": 0, "price": 100},
            {"id": "crab_blue", "name": "蓝蟹", "en": "Blue Crab", "cal": 87, "p": 18.1, "f": 1.1, "c": 0, "price": 40},
            {"id": "scallop_asian", "name": "扇贝", "en": "Scallop", "cal": 69, "p": 12.1, "f": 0.5, "c": 3.2, "price": 50},
            {"id": "mussel_asian", "name": "青口贝", "en": "Mussel", "cal": 86, "p": 12.0, "f": 2.2, "c": 3.7, "price": 25},
            {"id": "clam_littleneck", "name": "小蛤蜊", "en": "Littleneck Clam", "cal": 56, "p": 10.0, "f": 0.8, "c": 2.6, "price": 20},
            {"id": "clam_quahog", "name": "大蛤蜊", "en": "Quahog Clam", "cal": 56, "p": 10.0, "f": 0.8, "c": 2.6, "price": 25},
            {"id": "oyster", "name": "牡蛎", "en": "Oyster", "cal": 68, "p": 7.1, "f": 2.3, "c": 3.9, "price": 30},
            {"id": "cockle", "name": "鸟蛤", "en": "Cockle", "cal": 56, "p": 10.0, "f": 0.8, "c": 2.6, "price": 20},
            {"id": "abalone", "name": "鲍鱼", "en": "Abalone", "cal": 105, "p": 17.1, "f": 0.8, "c": 6.0, "price": 100},
            {"id": "conch", "name": "海螺", "en": "Conch", "cal": 130, "p": 26.0, "f": 1.2, "c": 1.7, "price": 35},
            {"id": "squid_asian", "name": "鱿鱼", "en": "Squid", "cal": 92, "p": 18.0, "f": 1.4, "c": 3.1, "price": 25},
            {"id": "octopus_asian", "name": "章鱼", "en": "Octopus", "cal": 82, "p": 14.9, "f": 1.0, "c": 2.2, "price": 30},
            {"id": "cuttlefish", "name": "墨鱼", "en": "Cuttlefish", "cal": 79, "p": 16.2, "f": 0.7, "c": 0.8, "price": 25},
            {"id": "sea_urchin", "name": "海胆", "en": "Sea Urchin", "cal": 172, "p": 13.3, "f": 11.8, "c": 4.8, "price": 120},
            {"id": "geoduck", "name": "象拔蚌", "en": "Geoduck", "cal": 75, "p": 15.0, "f": 0.5, "c": 2.0, "price": 150},
        ],
        "dried_seafood": [
            {"id": "dried_shrimp_asian", "name": "虾米", "en": "Dried Shrimp", "cal": 250, "p": 55.0, "f": 2.6, "c": 0, "price": 50},
            {"id": "dried_scallop_asian", "name": "干贝", "en": "Dried Scallop", "cal": 290, "p": 63.0, "f": 3.2, "c": 5.0, "price": 120},
            {"id": "dried_squid", "name": "鱿鱼干", "en": "Dried Squid", "cal": 320, "p": 60.0, "f": 4.0, "c": 5.0, "price": 45},
            {"id": "dried_abalone", "name": "干鲍鱼", "en": "Dried Abalone", "cal": 310, "p": 55.0, "f": 3.0, "c": 10.0, "price": 300},
            {"id": "dried_sea_cucumber", "name": "干海参", "en": "Dried Sea Cucumber", "cal": 300, "p": 50.0, "f": 1.0, "c": 15.0, "price": 250},
            {"id": "fish_maw", "name": "鱼胶", "en": "Fish Maw", "cal": 280, "p": 60.0, "f": 1.0, "c": 5.0, "price": 200},
        ],
    },
    "grains": {
        "rice": [
            {"id": "jasmine", "name": "茉莉香米", "en": "Jasmine Rice", "cal": 130, "p": 2.7, "f": 0.3, "c": 28.0, "price": 8},
            {"id": "basmati", "name": "印度香米", "en": "Basmati Rice", "cal": 130, "p": 2.7, "f": 0.3, "c": 28.0, "price": 10},
            {"id": "sushi_rice", "name": "寿司米", "en": "Sushi Rice", "cal": 130, "p": 2.5, "f": 0.3, "c": 28.5, "price": 12},
            {"id": "arborio", "name": "意大利圆米", "en": "Arborio Rice", "cal": 130, "p": 2.5, "f": 0.3, "c": 28.5, "price": 15},
            {"id": "wild_rice", "name": "野生米", "en": "Wild Rice", "cal": 101, "p": 4.0, "f": 0.3, "c": 21.3, "price": 25},
            {"id": "black_rice", "name": "黑米", "en": "Black Rice", "cal": 130, "p": 3.5, "f": 1.0, "c": 26.0, "price": 12},
            {"id": "red_rice", "name": "红米", "en": "Red Rice", "cal": 120, "p": 3.0, "f": 0.8, "c": 25.0, "price": 10},
            {"id": "brown_rice_asian", "name": "糙米", "en": "Brown Rice", "cal": 112, "p": 2.3, "f": 0.8, "c": 23.0, "price": 6},
        ],
        "wheat": [
            {"id": "semolina", "name": "粗粒小麦粉", "en": "Semolina", "cal": 360, "p": 12.7, "f": 1.1, "c": 72.8, "price": 8},
            {"id": "bread_flour", "name": "高筋面粉", "en": "Bread Flour", "cal": 361, "p": 12.0, "f": 1.0, "c": 72.5, "price": 6},
            {"id": "cake_flour", "name": "低筋面粉", "en": "Cake Flour", "cal": 362, "p": 8.0, "f": 0.8, "c": 76.3, "price": 8},
            {"id": "whole_wheat", "name": "全麦面粉", "en": "Whole Wheat Flour", "cal": 340, "p": 13.2, "f": 2.5, "c": 72.0, "price": 7},
            {"id": "couscous", "name": "库斯库斯", "en": "Couscous", "cal": 176, "p": 6.0, "f": 0.2, "c": 36.5, "price": 12},
            {"id": "bulgur", "name": "碾碎干麦", "en": "Bulgur", "cal": 83, "p": 3.1, "f": 0.2, "c": 18.6, "price": 10},
            {"id": "farro", "name": "法老麦", "en": "Farro", "cal": 170, "p": 7.0, "f": 1.0, "c": 34.0, "price": 18},
            {"id": "spelt", "name": "斯佩尔特小麦", "en": "Spelt", "cal": 338, "p": 15.0, "f": 2.4, "c": 70.2, "price": 15},
        ],
        "corn": [
            {"id": "corn_kernels", "name": "玉米粒", "en": "Corn Kernels", "cal": 86, "p": 3.3, "f": 1.4, "c": 19.0, "price": 6},
            {"id": "corn_cob", "name": "玉米棒", "en": "Corn on the Cob", "cal": 86, "p": 3.3, "f": 1.4, "c": 19.0, "price": 4},
            {"id": "polenta", "name": "玉米糊", "en": "Polenta", "cal": 70, "p": 1.6, "f": 0.4, "c": 15.0, "price": 8},
            {"id": "cornmeal", "name": "玉米粉", "en": "Cornmeal", "cal": 370, "p": 6.9, "f": 3.9, "c": 79.0, "price": 6},
            {"id": "masa", "name": "玛莎粉", "en": "Masa", "cal": 365, "p": 8.0, "f": 3.7, "c": 76.6, "price": 10},
        ],
        "other_grain": [
            {"id": "quinoa", "name": "藜麦", "en": "Quinoa", "cal": 120, "p": 4.4, "f": 1.9, "c": 21.3, "price": 25},
            {"id": "millet", "name": "小米", "en": "Millet", "cal": 119, "p": 3.5, "f": 1.0, "c": 23.7, "price": 6},
            {"id": "sorghum", "name": "高粱", "en": "Sorghum", "cal": 329, "p": 10.4, "f": 3.5, "c": 72.1, "price": 8},
            {"id": "teff", "name": "苔麸", "en": "Teff", "cal": 367, "p": 13.3, "f": 2.4, "c": 73.1, "price": 30},
            {"id": "amaranth_grain", "name": "苋菜籽", "en": "Amaranth", "cal": 371, "p": 13.6, "f": 7.0, "c": 65.3, "price": 25},
            {"id": "buckwheat", "name": "荞麦", "en": "Buckwheat", "cal": 343, "p": 13.3, "f": 3.4, "c": 71.5, "price": 10},
            {"id": "barley", "name": "大麦", "en": "Barley", "cal": 354, "p": 12.5, "f": 2.3, "c": 73.5, "price": 6},
            {"id": "rye", "name": "黑麦", "en": "Rye", "cal": 338, "p": 10.3, "f": 1.6, "c": 75.9, "price": 8},
        ],
    },
    "legumes": [
        {"id": "chickpea", "name": "鹰嘴豆", "en": "Chickpea", "cal": 164, "p": 8.9, "f": 2.6, "c": 27.4, "price": 10},
        {"id": "lentil_green", "name": "绿扁豆", "en": "Green Lentil", "cal": 116, "p": 9.0, "f": 0.4, "c": 20.1, "price": 12},
        {"id": "lentil_red", "name": "红扁豆", "en": "Red Lentil", "cal": 116, "p": 9.0, "f": 0.4, "c": 20.1, "price": 12},
        {"id": "black_bean", "name": "黑豆", "en": "Black Bean", "cal": 132, "p": 8.9, "f": 0.5, "c": 23.7, "price": 8},
        {"id": "kidney_bean", "name": "芸豆", "en": "Kidney Bean", "cal": 127, "p": 8.7, "f": 0.5, "c": 22.8, "price": 7},
        {"id": "pinto_bean", "name": "斑豆", "en": "Pinto Bean", "cal": 143, "p": 9.0, "f": 0.7, "c": 26.2, "price": 8},
        {"id": "navy_bean", "name": "白豆", "en": "Navy Bean", "cal": 140, "p": 8.2, "f": 0.6, "c": 26.1, "price": 8},
        {"id": "lima_bean", "name": "利马豆", "en": "Lima Bean", "cal": 113, "p": 7.8, "f": 0.4, "c": 20.2, "price": 10},
        {"id": "fava_bean", "name": "蚕豆", "en": "Fava Bean", "cal": 88, "p": 7.6, "f": 0.4, "c": 17.6, "price": 8},
        {"id": "edamame_asian", "name": "毛豆", "en": "Edamame", "cal": 121, "p": 11.9, "f": 5.2, "c": 8.9, "price": 8},
        {"id": "black_eyed_pea", "name": "豇豆", "en": "Black-eyed Pea", "cal": 116, "p": 7.7, "f": 0.5, "c": 20.8, "price": 7},
        {"id": "split_pea", "name": "黄豌豆", "en": "Split Pea", "cal": 118, "p": 8.3, "f": 0.4, "c": 21.1, "price": 7},
        {"id": "pigeon_pea", "name": "木豆", "en": "Pigeon Pea", "cal": 121, "p": 7.2, "f": 0.4, "c": 23.2, "price": 10},
        {"id": "mung_bean", "name": "绿豆", "en": "Mung Bean", "cal": 105, "p": 7.0, "f": 0.4, "c": 19.2, "price": 6},
        {"id": "adzuki_bean", "name": "红豆", "en": "Adzuki Bean", "cal": 128, "p": 7.5, "f": 0.1, "c": 25.0, "price": 8},
        {"id": "soybean", "name": "黄豆", "en": "Soybean", "cal": 173, "p": 16.6, "f": 9.0, "c": 9.9, "price": 6},
        {"id": "peanut_legume", "name": "花生", "en": "Peanut", "cal": 567, "p": 25.8, "f": 49.2, "c": 16.1, "price": 8},
    ],
    "herbs": [
        {"id": "basil", "name": "罗勒", "en": "Basil", "cal": 23, "p": 3.2, "f": 0.6, "c": 2.7, "price": 10},
        {"id": "cilantro", "name": "香菜", "en": "Cilantro", "cal": 23, "p": 2.1, "f": 0.5, "c": 3.7, "price": 5},
        {"id": "mint", "name": "薄荷", "en": "Mint", "cal": 44, "p": 3.3, "f": 0.7, "c": 8.4, "price": 8},
        {"id": "parsley", "name": "欧芹", "en": "Parsley", "cal": 36, "p": 3.0, "f": 0.8, "c": 6.3, "price": 8},
        {"id": "dill", "name": "莳萝", "en": "Dill", "cal": 43, "p": 3.5, "f": 1.1, "c": 7.0, "price": 10},
        {"id": "rosemary", "name": "迷迭香", "en": "Rosemary", "cal": 131, "p": 3.3, "f": 5.9, "c": 20.7, "price": 12},
        {"id": "thyme", "name": "百里香", "en": "Thyme", "cal": 101, "p": 5.6, "f": 1.7, "c": 24.5, "price": 12},
        {"id": "oregano", "name": "牛至", "en": "Oregano", "cal": 265, "p": 9.0, "f": 4.3, "c": 68.9, "price": 12},
        {"id": "sage", "name": "鼠尾草", "en": "Sage", "cal": 315, "p": 10.6, "f": 12.7, "c": 60.7, "price": 15},
        {"id": "tarragon", "name": "龙蒿", "en": "Tarragon", "cal": 295, "p": 22.8, "f": 7.2, "c": 50.0, "price": 18},
        {"id": "bay_leaf", "name": "月桂叶", "en": "Bay Leaf", "cal": 313, "p": 7.6, "f": 8.4, "c": 75.0, "price": 10},
        {"id": "lemongrass", "name": "香茅", "en": "Lemongrass", "cal": 99, "p": 1.8, "f": 0.5, "c": 25.3, "price": 12},
        {"id": "kaffir_lime", "name": "青柠叶", "en": "Kaffir Lime Leaf", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 15},
        {"id": "curry_leaf", "name": "咖喱叶", "en": "Curry Leaf", "cal": 108, "p": 6.0, "f": 1.0, "c": 18.7, "price": 15},
        {"id": "shiso", "name": "紫苏", "en": "Shiso", "cal": 37, "p": 3.8, "f": 0.7, "c": 6.0, "price": 12},
        {"id": "chive_blossom", "name": "韭菜花", "en": "Chive Blossom", "cal": 30, "p": 3.3, "f": 0.7, "c": 4.4, "price": 15},
    ],
    "spices": [
        {"id": "black_pepper", "name": "黑胡椒", "en": "Black Pepper", "cal": 251, "p": 10.4, "f": 3.3, "c": 63.9, "price": 15},
        {"id": "white_pepper", "name": "白胡椒", "en": "White Pepper", "cal": 296, "p": 10.4, "f": 2.1, "c": 68.6, "price": 18},
        {"id": "sichuan_pepper_spice", "name": "花椒", "en": "Sichuan Pepper", "cal": 296, "p": 6.7, "f": 8.9, "c": 68.3, "price": 25},
        {"id": "pink_pepper", "name": "粉红胡椒", "en": "Pink Pepper", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 30},
        {"id": "allspice", "name": "多香果", "en": "Allspice", "cal": 263, "p": 6.1, "f": 8.7, "c": 72.1, "price": 20},
        {"id": "cardamom", "name": "小豆蔻", "en": "Cardamom", "cal": 311, "p": 10.8, "f": 6.7, "c": 68.5, "price": 40},
        {"id": "clove", "name": "丁香", "en": "Clove", "cal": 274, "p": 6.0, "f": 13.0, "c": 65.5, "price": 25},
        {"id": "nutmeg", "name": "肉豆蔻", "en": "Nutmeg", "cal": 525, "p": 5.8, "f": 36.3, "c": 49.3, "price": 30},
        {"id": "mace", "name": "肉豆蔻皮", "en": "Mace", "cal": 475, "p": 6.7, "f": 32.4, "c": 50.5, "price": 35},
        {"id": "coriander_seed", "name": "芫荽籽", "en": "Coriander Seed", "cal": 298, "p": 12.4, "f": 17.8, "c": 55.0, "price": 12},
        {"id": "fennel_seed", "name": "茴香籽", "en": "Fennel Seed", "cal": 345, "p": 15.8, "f": 14.9, "c": 52.3, "price": 15},
        {"id": "mustard_seed", "name": "芥末籽", "en": "Mustard Seed", "cal": 508, "p": 26.1, "f": 36.2, "c": 28.1, "price": 12},
        {"id": "sesame_seed", "name": "芝麻", "en": "Sesame Seed", "cal": 573, "p": 17.7, "f": 49.7, "c": 23.5, "price": 15},
        {"id": "poppy_seed", "name": "罂粟籽", "en": "Poppy Seed", "cal": 525, "p": 18.0, "f": 41.6, "c": 28.1, "price": 25},
        {"id": "caraway", "name": "葛缕子", "en": "Caraway", "cal": 333, "p": 19.8, "f": 14.6, "c": 49.9, "price": 18},
        {"id": "dill_seed", "name": "莳萝籽", "en": "Dill Seed", "cal": 305, "p": 16.0, "f": 14.5, "c": 55.2, "price": 15},
        {"id": "celery_seed", "name": "芹菜籽", "en": "Celery Seed", "cal": 392, "p": 18.1, "f": 25.3, "c": 41.4, "price": 18},
        {"id": "fenugreek", "name": "胡芦巴", "en": "Fenugreek", "cal": 323, "p": 23.0, "f": 6.4, "c": 58.4, "price": 15},
        {"id": "asafoetida", "name": "阿魏", "en": "Asafoetida", "cal": 297, "p": 4.0, "f": 1.1, "c": 67.8, "price": 30},
        {"id": "sumac", "name": "漆树粉", "en": "Sumac", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 25},
        {"id": "zaatar", "name": "扎塔尔", "en": "Za'atar", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 20},
        {"id": "dukkah", "name": "杜卡", "en": "Dukkah", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 25},
        {"id": "garam_masala", "name": "印度综合香料", "en": "Garam Masala", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 20},
        {"id": "chinese_five_spice", "name": "五香粉", "en": "Chinese Five Spice", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 15},
        {"id": "herbes_de_provence", "name": "普罗旺斯香草", "en": "Herbes de Provence", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 20},
        {"id": "old_bay", "name": "老湾调味料", "en": "Old Bay", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 18},
        {"id": "tajin", "name": "塔欣调味料", "en": "Tajín", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 15},
        {"id": "shichimi", "name": "七味粉", "en": "Shichimi", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 20},
        {"id": "togarashi", "name": "一味粉", "en": "Togarashi", "cal": 0, "p": 0, "f": 0, "c": 0, "price": 18},
    ],
}

def create_ingredient_file(category, subcategory, item):
    """创建单个食材文件"""
    dir_path = KNOWLEDGE_DIR / category / subcategory
    dir_path.mkdir(parents=True, exist_ok=True)
    
    file_path = dir_path / f"{item['id']}.json"
    
    data = {
        "id": item["id"],
        "name": item["name"],
        "name_en": item["en"],
        "category": category,
        "subcategory": subcategory,
        "nutrition_per_100g": {
            "calories": item["cal"],
            "protein": item["p"],
            "fat": item["f"],
            "carbs": item["c"],
            "fiber": 0
        },
        "price_range": {
            "min": int(item["price"] * 0.7),
            "max": int(item["price"] * 1.3),
            "average": item["price"],
            "unit": "元/斤",
            "last_updated": "2024-01-15"
        },
        "seasonal_availability": {
            "全年": True,
            "best_season": None
        },
        "storage": {
            "fresh": "按照食材特性保存",
            "tips": "参考食材说明"
        },
        "pairing": {
            "classic": [],
            "usage": []
        },
        "tips": []
    }
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def main():
    """主函数"""
    count = 0
    
    for category, subcategories in GLOBAL_INGREDIENTS.items():
        if isinstance(subcategories, list):
            for item in subcategories:
                create_ingredient_file(category, "general", item)
                count += 1
        else:
            for subcategory, items in subcategories.items():
                for item in items:
                    create_ingredient_file(category, subcategory, item)
                    count += 1
    
    print(f"✅ Created {count} ingredient files")
    print(f"📂 Total ingredient files: {len(list(KNOWLEDGE_DIR.rglob('*.json')))}")

if __name__ == "__main__":
    main()
